### ISSUE TITLE
HTTP Basic Authentication credentials in Google Chrome 64 not transfered to AJAX calls

### ISSUE THREAD

**Issue by mhuber84** [d3/d3-fetch#10]
Our project is protected by a HTTP Basic Authentication and we have to enter the username/password on every d3.json() call in Google Chrome.

It seems like in Google Chrome 64 the cached credentials are not transfered to the request, if `credentials: 'include'` is not set. I haven't found a real documentation for this, but there is a blog post: https://developers.google.com/web/updates/2015/03/introduction-to-fetch#sending_credentials_with_a_fetch_request

https://github.com/d3/d3-fetch/blob/d4bfe27d7462be87b423a4e4cb76a0b4cb9220cb/src/json.js#L7

**Comment by mhuber84** [comment]
[basicauth.zip](https://github.com/d3/d3-fetch/files/1682088/basicauth.zip) is a minimal test case for this issue.

This is almost, but not exactly, the same as my last issue: https://github.com/d3/d3-request/issues/33 ;-)

**Comment by mbostock** [comment]
Per the document, pass the *init* object to d3.json. For example:

```js
const data = await d3.json("path/to/file.json", {credentials: "include"});
```
