### ISSUE TITLE
polyfill fetch and promise

### ISSUE THREAD

**Issue by russellgoldenberg** [d3/d3-fetch#11]
Fetch / promise [aren't supported](https://caniuse.com/#search=fetch) in older IE / iOS with decent usage. I'm assuming you'll need to add the polyfill or does v5 drop support for these?

**Comment by mbostock** [comment]
D3 does not include any polyfills, so if you want to support browsers that do not support the Fetch API, you’ll need to include a polyfill before loading D3.
