### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by tsando** [d3/d3-fetch#19]
I have a node application but when I try to use this to use d3.csv, I get `ReferenceError: fetch is not defined`. I'm simply doing this after `npm install d3-fetch` (this installed version 1.1.0):

```
var d3 = require("d3-fetch")
d3.csv("/data/csvs/timeline.csv").then(function (data) {console.log(data)});
```

I also tried installing `fetch` as `npm install fetch` but then the error became `TypeError: fetch is not a function`

Thanks for your help.

**Comment by mbostock** [comment]
You need an environment that supports the [Fetch API](https://fetch.spec.whatwg.org/), such as a a web browser. Node does not currently support Fetch, though it may in the future. If you want to load this library in an environment that does not natively support Fetch you will need to load your own polyfill such as [node-fetch](https://www.npmjs.com/package/node-fetch).

**Comment by stevage** [comment]
It's probably worth documenting how to make this work. I had to fiddle a bit, but this worked after `npm install node-fetch-polyfill`:

```
if (typeof fetch !== 'function') {
    global.fetch = require('node-fetch-polyfill');
}
const csv = require('d3-fetch').csv;
```

**Comment by jomasim** [comment]
You need to install jsdom using yarn or npm.
Node.js does not support dom by default, thus the need to use jsdom for creating dom elements. Use d3 for all other manipulations except fetch operations. i.e d3.xml,d3.tsv 

```
import jsdom from 'jsdom';
import * as d3 from 'd3';
const { JSDOM } = jsdom;
JSDOM.fromURL(
    'your resource url',
  ).then((dom) => {
    const doc = dom.window.document;
    const states = d3
      .select(doc)
      .select('path')
      .attr(':fme:ID');
    console.log(states);
  });
```
creating dom from file

```
JSDOM.fromURL(
    'your resource url',
  ).then((dom) => {
    const doc = dom.window.document;
}
```

dom from html string

```
const dom = new JSDOM(
  `<p>Hello
    <img src="foo.jpg">
  </p>`,
  { includeNodeLocations: true }
);

```

**Comment by linglp** [comment]
> if (typeof fetch !== 'function') {
>     global.fetch = require('node-fetch-polyfill');
> }

This does not work for me :(
