### ISSUE TITLE
Documentation gap for POST between d3-request and d3-fetch

### ISSUE THREAD

**Issue by steveharoz** [d3/d3-fetch#22]
Here's an example from the [d3-request readme](https://github.com/d3/d3-request):

```
d3.request("/path/to/resource")
    .header("X-Requested-With", "XMLHttpRequest")
    .header("Content-Type", "application/x-www-form-urlencoded")
    .post("a=2&b=3", callback);
```

But based on the d3-fetch readme, it's unclear if it's possible to post data. Given that the d3-request readme says to use d3-fetch instead, it'd be good to either have "translated" versions of examples that send data or point to other code/libraries with that functionality.

**Comment by mbostock** [comment]
It is, but you’ll have to teach yourself the [Fetch API](https://fetch.spec.whatwg.org/), which d3-fetch is built on. Googling “post with fetch” suggests a few useful tutorials:

https://googlechrome.github.io/samples/fetch-api/fetch-post.html

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Here’s a little notebook I made to demonstrate:

https://beta.observablehq.com/@mbostock/posting-with-fetch

I’ll link some more recipe notebooks from the README when I have time.
