### ISSUE TITLE
JSON fetching discrepancy between v4 and v5

### ISSUE THREAD

**Issue by misimpso** [d3/d3-fetch#23]
When using d3.json in d3 v5, reading in a json file it gives me:
`Fetch API cannot load file:///H:/Code/Dashboard/js/jsonOutput.json. URL scheme "file" is not supported.`

However when I move back to d3 v4, using the same d3.json code, it works fine and reads the file contents.

I am developing in Adobe Brackets which handles cross origin requests, so it seems d3 is mishandling it somehow.

**Comment by mbostock** [comment]
The Fetch API does not support local file access, so you’ll either need to use d3-request or XMLHttpRequest directly, or use a web server to access your files.

**Comment by RPellowski** [comment]
But d3-request says:
This module is deprecated as of D3 5.0; please use d3-fetch instead.

**Comment by RPellowski** [comment]
So are you saying there is no way to read a json file with v5? If there is, can you point to an example?

**Comment by mbostock** [comment]
@RPellowski There’s no way to do it using Fetch, which is what d3-fetch is built on; you need a local web server. Or you can use d3-request (or XMLHttpRequest directly) in addition to the D3 v5 default bundle.
