### ISSUE TITLE
Async await with d3 fetch functions?

### ISSUE THREAD

**Issue by dysol** [d3/d3-fetch#25]
Hi, is it not possible to use Async/Await with d3-fetch?

i tried doing this:

```
import * as d3Fetch from "d3-fetch";

async getData() {
     const india = await d3Fetch.json('/data/IND.json');

     return india;
    },
```

it returned a Promise instead.

PS: currently, i have to save .geojson as .json file format. Feels counter-intuitive? Any plans to add support to read .geojson files?

**Comment by mbostock** [comment]
Async-await works great with d3-fetch and we use it in Observable regularly. Here is an example I found:

https://beta.observablehq.com/@jermspeaks/async-await
