### ISSUE TITLE
d3.text() decode UTF-16

### ISSUE THREAD

**Issue by DDDgfx** [d3/d3-fetch#26]
I have several pipe delimited text files, that  I load and then concatenate before parsing with d3.dsv. I've been loading them asynchronously with d3.queue and d3.text. I've replaced my queue functionality but the new d3.text now does not properly decode these files which it turns out are UTF-16 LE. It worked well before.

There is no example of how to structure the init function but I have tried:

```
d3.text("/data.csv", { headers: { "Content-Type": "text/html, charset=UTF-16" } }).then(function(text) {
    console.log(text); 
});
```

But Im still getting a lot of this: �� and improperly parsed line endings.  Did d3.text() lose its decoding abilities? Should the above work?

**Comment by mbostock** [comment]
The [Fetch API](https://fetch.spec.whatwg.org/#concept-body-package-data) only supports UTF-8 for parsing text. However, you can fetch binary data and then use the [Encoding API](https://encoding.spec.whatwg.org/) to decode your UTF-16 LE.

https://beta.observablehq.com/@mbostock/fetch-utf-16

**Comment by DDDgfx** [comment]
Finally a question worthy of an answer. Thanks Mike.

**Comment by DDDgfx** [comment]
Can this work with promise.all?

**Comment by mbostock** [comment]
Yes, the Fetch API is promise-based.
