### ISSUE TITLE
Response's body lost when error is thrown

### ISSUE THREAD

**Issue by pavelschon** [d3/d3-fetch#27]
When the webserver sends response with JSON, but status code is other than 200 OK, then the returned JSON is unreachable.

Snipppet:
```javascript
d3.json(url).then(function(response) {
    console.log(response.data);
}).catch(function(err) {
    console.log(err.traceback);
});
```
Server responds:
```
500 Internal server error
{ "traceback": "some traceback here" }
```

In that case, it is not possible to extract the JSON from the response, because d3 throws error with text constructed from `response.status + " " + response.statusText`, but original response's body is lost.

Link to problematic line: https://github.com/d3/d3-fetch/blob/daaae6193919c21b999f5daa89a0223681c19463/src/json.js#L2

**Comment by mbostock** [comment]
Yep. If you want the response body, just call `fetch` directly instead of using d3.json.
