### ISSUE TITLE
d3.append returns undefined when appending result from xml()

### ISSUE THREAD

**Issue by mattgwwalker** [d3/d3-fetch#28]
When `d3.xml()` is used to download an asset, `selection.append(asset.documentElement)` returns `undefined` rather than "a new selection containing the appended elements" (as described in the documentation.

```javascript
var filename = "assets/game-interface.svg";

var assetLoadedPromise =
    d3.xml(filename);

assetLoadedPromise.then( asset => {
    // Insert asset                                                                                  
    var body = d3.select("body").node();

    var insertedAsset = body.append(asset.documentElement);

    // Check we have a reference to the inserted element                                             
    if (insertedAsset === undefined) {
        throw "insertedAsset is undefined";
    }
});
```

**Comment by mbostock** [comment]
You’re not calling *selection*.append in the provided code snippet. The body var is the return value from *selection*.node, so it would be the same as document.body, meaning you are calling append on an HTMLBodyElement.

**Comment by mbostock** [comment]
Here is a working example:

https://observablehq.com/d/471ddc749870ec93

And here is the documentation for *element*.append, which returns undefined:

https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append

**Comment by mattgwwalker** [comment]
Thank you for such a complete response.  It's greatly appreciated at this end.

Matthew
