### ISSUE TITLE
Is there going to be an on.("progress", ...) equivalent for d3 v5?

### ISSUE THREAD

**Issue by NucleaPeon** [d3/d3-fetch#31]
d3.js version 3 (and 4 I think), in the d3.requests module there is a way to hook into the progress of the request using `.on("progress", function(...) { ... });`, see this block: https://bl.ocks.org/mbostock/3750941

In d3 v5, no such equivalent exists as far as I know in the d3-fetch  library, only `.then(function(...) { ... });`. Is there a plan to implement or a workaround for this feature? Or are the limitations of underlying `fetch` preventing it from being usable?

Thanks

**Comment by mbostock** [comment]
This is just a tiny abstraction on top of the Fetch API (see the source), so you’d use the Fetch API to monitor progress. See this example:

https://observablehq.com/@mbostock/fetch-progress
