### ISSUE TITLE
Fix incompatibility with strict/safe CSP

### ISSUE THREAD

**Issue by tdelmas** [d3/d3-fetch#35]
https://github.com/d3/d3-fetch/blob/master/src/dsv.js use `csvParse` and `tsvParse` from "d3-dsv"

As explained in https://github.com/d3/d3-dsv/issues/65 by @mbostock : 

> I recommend using parseRows as suggested in the text you pasted from the README and a row function to turn the array of field values into an object.

Using  `csvParse` or `tsvParse` make it incompatible with CSP without `unsafe-eval`.

It impact for example plotly/plotly.js#897 (which use the old version of d3 "3.5.17" so "d3-request" and not this package, but "d3-request" has the exact same problem. I didn't opened an issue there as its status is "This module is deprecated as of D3 5.0; please use d3-fetch instead.")

Or is there another API from this package that can be used to avoid that problem?

**Comment by mbostock** [comment]
Use [d3.text](https://github.com/d3/d3-fetch/blob/master/README.md#text) or use fetch directly.

```js
d3.csvParseRows(await d3.text("path/to/file.csv"))
```

```js
fetch("path/to/file.csv")
  .then(response => response.text())
  .then(text => d3.csvParseRows(text))
```
