### ISSUE TITLE
d3.json interprets HTTP 204 as errors

### ISSUE THREAD

**Issue by DavidBruant** [d3/d3-fetch#38]
I was working on a project with @newick and @maiwann using the GIthub API and we used the [delete repo endpoint](https://developer.github.com/v3/repos/#delete-a-repository). This endpoint returns an HTTP 204 result on success with an empty body.

When calling `d3.json`, this results in a failing promise with an error indicating a `JSON.parse` error. This is probably due to trying to parse an empty string (which is not valid JSON)

We did not expect this outcome with a 204 (which is supposed to indicate success)

We solved our problem by using `d3.text` instead (which does not perform a parsing, so no error), but wondered whether it might make sense to change the behavior of `d3.json`, hence this issue

**Comment by mbostock** [comment]
See #18.

**Comment by DavidBruant** [comment]
oh i had missed that, sorry

**Comment by mbostock** [comment]
Folding into #18.
