### ISSUE TITLE
d3.json doesn't recognize my function as a RequestInit

### ISSUE THREAD

**Issue by mikwee** [d3/d3-fetch#47]
I wrote this code (much of it legally copied, to be fair):
```js
d3.json("./data.json", function (data) {
    // Add X axis
    var x = d3.scaleLinear()
      .domain([0, 13000])
      .range([ 0, width]);
    svg.append("g")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(x))
      .selectAll("text")
        .attr("transform", "translate(-10,0)rotate(-45)")
        .style("text-anchor", "end");
    // Y axis
    var y = d3.scaleBand()
      .range([ 0, height ])
      .domain(data.map(function(d) { return d.Country; }))
      .padding(.1);
    svg.append("g")
      .call(d3.axisLeft(y));
    
    svg.selectAll("myRect")
        .data(data)
        .enter();
});
```
But then I had to install `@types/d3` because it couldn't find a declaration file, and after that, that first line threw a `ts(2559)` error, saying: `Type '(data: any) => void' has no properties in common with type 'RequestInit'.`. This is how every tutorial says it's supposed to be written. What is happening? Thank you.

**Comment by Fil** [comment]
This is how it was working with older versions of D3, using https://github.com/d3/d3-request ; since d3@5 (released in March 2018) we moved to a promise-based system, using https://github.com/d3/d3-fetch instead
See https://github.com/d3/d3/blob/main/CHANGES.md#changes-in-d3-50 for details
