### ISSUE TITLE
Document init arg

### ISSUE THREAD

**Issue by DavidBruant** [d3/d3-fetch#6]
The readme lists functions that take an optional `init` argument, but never documents it.

**Comment by mbostock** [comment]
It’s part of the Fetch API: https://fetch.spec.whatwg.org

**Comment by DavidBruant** [comment]
Yes, and everywhere is written `If init is specified, it is passed along to the underlying call to fetch.`, not sure why i missed it, sorry

**Comment by mbostock** [comment]
I added some additional text and a more specific link for clarity.
